name: cypress
on: [push, pull_request]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npm run ci
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/results
            cypress/videos
            cypress/screenshots
